/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ringcentral;

public class MyWebSite {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new MyWebSite().getGreeting());
    }
}
